name: Add artifact links to pull request and related issues

on:
  workflow_run:
    workflows: [Build pistorm distro]
    types: [completed]
    
jobs:
  artifacts-url-comments:
    name: add artifact links to pull request and related issues job
    runs-on: ubuntu-latest
    steps:
      - name: Add artifact links to pull request and related issues step
        uses: tonyhallett/artifacts-url-comments@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          prefix: SD card image for testing
          suffix: THIS IS NOT A RELEASE
          format: name
          addTo: pullandissues
