name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache poky
        uses: actions/cache@v2
        with:
          path: poky
          key: ${{ runner.os }}-poky

      - name: Cache build build
        uses: actions/cache@v2
        with:
          path: build
          key: ${{ runner.os }}-build

      - name: Prepare build environment
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo debconf-set-selections .github/workflows/debconf_selections
          sudo apt update
          sudo apt -y upgrade
          sudo apt -y install --no-install-recommends build-essential chrpath diffstat gawk libncurses5-dev python3-distutils texinfo

      - name: Build distro
        run: ./build.sh
